### ISSUE TITLE
Question about a project of you.

### ISSUE THREAD

**Issue by NicciZar** [axdra/axdra#1]
Hello Axdra,

Sorry that I have to open an Issue here on your page but I have a question about a project that you started. (and I don't know any other way to contact a person on github)

The BlazoriLO - Its not available anymore and I was wondering If you still have a working version of this to test (or a release of some sort)

I have an ILO2 and browser compatibility is pretty bad... (I am using an old Version of Firefox currently)

**Comment by axdra** [comment]
Hi!

No worries about writing here, the project did have some working builds back when it was in development. But the code is no longer compatible with Blazor, Microsoft did some breaking changes to it. Right now I do not have any time or reason to continue on the project. But maybe in the future, because iLO 2 is just losing more and more of it's existence because of new browsers/Java versions not supporting it. 

Sorry for the inconvenience.

//
Axel

**Comment by NicciZar** [comment]
Hey

Thank you for the info. 
It would be great if the unsupported protocols that HP uses could be changed to supported ones that the newer browsers use..

The strange thing is that I used a ILO1 a few days ago and it was working fine with new browsers...
